### ISSUE TITLE
배고파요

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#1]
저의 배를 채워주세요

**Comment by YangHeeChang** [comment]
굶으세요

**Comment by jeongseonwoong** [comment]
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/c75e5f86-741f-4daa-8cde-d3ce720727ea)

**Comment by jeongseonwoong** [comment]
내공주세요

**Comment by JJW1223** [comment]
사주시면 내공 드리겠습니다 감사합니다
