### ISSUE TITLE
main페이지 사진 크기 및 위치 조정 필요?

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#102]
![스크린샷 2024-05-24 003339](https://github.com/jeongseonwoong/morbus/assets/84493979/ee02682f-3e69-4c88-97e1-a0f6256c481f)
![스크린샷 2024-05-24 003347](https://github.com/jeongseonwoong/morbus/assets/84493979/3757b431-fbc3-4980-8453-a2706fe31ed1)
창 크기에 따라 사진끼리 겹치는 등 보기 이상해집니다.

**Comment by JJW1223** [comment]
확인해보고 말씀드리겠습니다

**Comment by jeongseonwoong** [comment]
빠른 페이지 로딩을 위해 script태그 </body> 바로 위로 옮겨주시면 감사하겠습니다.

**Comment by YangHeeChang** [comment]
#125
