### ISSUE TITLE
기말고사 발표

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#110]
기말고사 발표 관련해서 기말고사 기간이 더 가까워 지기 전에 모여서 회의 한번 하고싶습니다. 이번 주 중에 한번 가능할까요?( ☆일주일의 시작은 일요일이다)

**Comment by YangHeeChang** [comment]
평일 가능합니다

**Comment by YangHeeChang** [comment]
이번 주 수요일 빼고

**Comment by jeongseonwoong** [comment]
월요일 어떤가요?

**Comment by JJW1223** [comment]
ㅘ 일주일의 시작이 일요일이였다니.. 월요일 ㄱㄱ
