### ISSUE TITLE
로그인 시 증상기록지 이용

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#112]
증상기록지 이용 할 때, 로그인 되어있는 상태에서만 이용가능하게 할까 고민 중인데 어떻게 생각하시나요?

**Comment by YangHeeChang** [comment]
![스크린샷 2024-05-26 134514](https://github.com/jeongseonwoong/morbus/assets/84493979/90b5e878-fa92-4a73-a6cc-ed5a531a2d1f)
로그인 안하면 이용할 수 없게 구현해봄

**Comment by jeongseonwoong** [comment]
좋습니다

**Comment by YangHeeChang** [comment]
#115
