### ISSUE TITLE
morbus 위치를 조정할 필요가 있어 보입니다.

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#117]
![스크린샷 2024-05-27 202546](https://github.com/jeongseonwoong/morbus/assets/84493979/5210fe94-f6d0-4635-a031-eabccc5da8a1)
창 크기를 일정 크기 이하로 줄이면 morbus로고 위치가 왼쪽으로 붙습니다.

**Comment by JJW1223** [comment]
해결했습니다

**Comment by YangHeeChang** [comment]
굿
