### ISSUE TITLE
로그인 페이지에서 다른 페이지로 넘어가는 버튼 누를 시 오류 발생

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#120]
![스크린샷 2024-05-29 145745](https://github.com/jeongseonwoong/morbus/assets/84493979/63a00770-d9d4-4f9c-90db-c4f70d4033c0)
![스크린샷 2024-05-29 145758](https://github.com/jeongseonwoong/morbus/assets/84493979/0ddfcfb1-cccb-4a1b-a9fc-8f383aa2c95d)
![스크린샷 2024-05-29 145806](https://github.com/jeongseonwoong/morbus/assets/84493979/3ea4313f-fe68-4aef-a177-a08041e571da)
로그인 페이지 상단의 버튼 누를 시 사진과 같은 오류페이지가 나옴

**Comment by jeongseonwoong** [comment]
pull 받고 다시해보세요

**Comment by YangHeeChang** [comment]
html확장자명 제거 시 정상작동합니다.
