### ISSUE TITLE
로그인이랑 회원가입 페이지의 디자인 통일

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#121]
![스크린샷 2024-05-29 184008](https://github.com/jeongseonwoong/morbus/assets/84493979/2748718b-33cf-45c2-a5fe-4311cd341097)
로그인 페이지랑 회원가입 페이지랑 디자인을 똑같이 만들었는데, 어떤가요?

**Comment by JJW1223** [comment]
디자인 통일 면에서 좋은 것 같습니다

**Comment by jeongseonwoong** [comment]
좋습니다
