### ISSUE TITLE
페이지 양쪽 빈칸에 광고 베너

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#124]
페이지 양쪽 빈칸에 광고 베너 다는 거 어떨까요? 디자인 할 것도 마땅치 않고 다른 사이트 들은 그 자리에 광고 다는 것 같던데
![1717037137017](https://github.com/jeongseonwoong/morbus/assets/84301208/c50332ef-cd8c-48e5-80d5-8c24c0bb19d1)
예시로 적용해봤습니다.

**Comment by JJW1223** [comment]
상당히 인상적이네요

**Comment by YangHeeChang** [comment]
좋네요
