### ISSUE TITLE
UnitTest Coverage

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#137]
유닛 테스트 실행 전에 README.md의 h2 설치, 설정 실행 해주시기 바랍니다.
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/4e6ce8a3-105d-41ed-a140-8070402c4968)
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/dac33bbd-2297-4759-b939-3fb4138d90fe)
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/f12b5620-8465-4ce5-949e-08b91209fa27)
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/2449173c-5bd3-4d20-b215-f18592f6169f)
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/1809551e-00fd-4b80-9644-9ff30efce428)
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/eb9e67c3-427e-4e92-9da2-8fd43f46f427)
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/ea0dae9e-30e9-4cf2-9f15-29eff9ca8527)
morbus/Server 디렉토리로 이동
```sh
~$./gradlew clean test
```
build.reports 하위에 jacoco directory 생성됨.
jacoco.test.html.index.html 브라우저를 브라우저로 열면 확인 가능하다.
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/7c1edf3f-33fa-4be7-a510-0415a95de622)

**Comment by JJW1223** [comment]
이상 java 유닛테스트입니다
