### ISSUE TITLE
로그아웃 버튼이 아래로 내려가 있습니다.

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#144]
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/8db8896b-66f0-41c3-b39b-0b2094e402d6)
고쳐야할 것 같습니다.

**Comment by JJW1223** [comment]
해당 태그 margin-top 조정해서 바꾸셔야 할 것 같습니다.

**Comment by JJW1223** [comment]
해결 완료했습니다
