### ISSUE TITLE
증상 기록지 morbus 로고 안보임

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#23]
spring 사용하면서 local 폴더 안에 있는 이미지를 못 불러 오는 것 같습니다...
인터넷 찾아봤는데 방법이 조금 어려워서 그냥 template 폴더에 사진 폴더 붙혀넣기로 하나 더 만들면 되긴 하는데 그렇게 할까요?ㅠ

**Comment by YangHeeChang** [comment]
파일 추가 및 경로 변경 완료
