### ISSUE TITLE
morbus.html css 버그

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#26]
morbus.html 23번째                   
float: top;  갑자기 오류가 뜹니다.
![image](https://github.com/jeongseonwoong/morbus/assets/84301208/ed0012d1-ece7-4a14-8823-4290bc9db44b)

**Comment by JJW1223** [comment]
left로 바꾸어 해결하시면 될거같습니다.

**Comment by jeongseonwoong** [comment]
감사합니다.
