### ISSUE TITLE
org.json package does not exist 버그

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#27]
org.json이 존재하지 않는 버그입니다.
![스크린샷 2024-04-24 134121](https://github.com/jeongseonwoong/morbus/assets/85469701/b5961150-9550-4281-8cd6-7fd66bb05c3c)

**Comment by JJW1223** [comment]
추가로 feature_symptompageDeco PR 점검 중 발생한 문제입니다.

**Comment by jeongseonwoong** [comment]
JSONException 없애보세요
