### ISSUE TITLE
Syptom.html 페이지 한글 깨짐 버그

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#28]
아래 사진과 같이 한글이 깨져서 나오는 버그가 있습니다.
![스크린샷 2024-04-24 154356](https://github.com/jeongseonwoong/morbus/assets/85469701/e7fb2d98-de93-46ac-aa10-0410bbbf8ffb)

**Comment by jeongseonwoong** [comment]
https://www.jetbrains.com/ko-kr/community/education/#students 
링크에서 intellij ultimate로 바꾸고 실행해보세요

**Comment by JJW1223** [comment]
알겠습니다 한번 시도해보겠습니다

**Comment by JJW1223** [comment]
오 해결됐습니다
