### ISSUE TITLE
IntelliJ IDEA에서 git pull 받는 법

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#30]
IntelliJ IDEA에서 git pull 어떻게 받나요?

**Comment by jeongseonwoong** [comment]
조조진진우우씨가 잘 알던데

**Comment by JJW1223** [comment]
![스크린샷(4)](https://github.com/jeongseonwoong/morbus/assets/85469701/e8edbe8d-a4a3-47e0-a890-0e0c09d6b01c)
pull 받을 브랜치를 checkout하시고, 왼쪽 상단에 git 메뉴에 pull 옵션이 있는데 누르시면 스크린샷처럼 뜹니다.  여기서 pull 내용을 받을 브랜치를 선택하시고 pull받으시면 됩니다.
