### ISSUE TITLE
다른 html 파일로 이동이 안되는 오류

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#36]
보통 html에서는 <a>를 사용해서 다른 html 파일로 이동을 합니다.
원래라면 바로 template 하위 파일에서 동일한 이름을 가진 html 파일을 찾아서 이동하겠지만 이번 프로젝트에서는 Spring을 사용중이여서 중간에 한 단계를 더 거칩니다.

기존
1.<a href = "/something>
2. template 하위 something.html 찾기
3. something.html 파일로 이동

Spring 이용 시
1.<a href = "/something>
2. something을 받는 컨트롤러로 이동
3. 컨트롤러에서 파일이름 "something" 리턴
4. template 하위 something.html 찾기
5. something.html 파일로 이동

ㅁ. 해결 방법
java.morbus.controller.MorbusController파일로 이동

@GetMapping("이동하려는 파일이름")
public String 함수이름()
{
//Model model을 통해서 필요한 값을 받을 수도 있다.
   return "이동하려는 파일이름";
}

위의 함수를 MorbusController 파일에 추가해주시면 됩니다.

**Comment by JJW1223** [comment]
감삼다
