### ISSUE TITLE
main pull 했을 때, localhost가 열리지 않고 코드가 끝나는 버그

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#43]
프로그램을 run했을 때 localhost가 열리지 않고 코드가 끝납니다.
![스크린샷 2024-05-02 174715](https://github.com/jeongseonwoong/morbus/assets/85469701/b080c759-8ccb-409c-9577-aba55c708f1b)
![스크린샷 2024-05-02 174817](https://github.com/jeongseonwoong/morbus/assets/85469701/83cc4b42-0aa7-4553-85a5-df2381263964)
![스크린샷 2024-05-02 175000](https://github.com/jeongseonwoong/morbus/assets/85469701/d66b5c93-a928-49bc-9516-32f38112acea)
![스크린샷 2024-05-02 175028](https://github.com/jeongseonwoong/morbus/assets/85469701/72f0b205-b84c-483e-9f17-ddc893695f60)
오류 내용 화면입니다

**Comment by jeongseonwoong** [comment]
코드 바꿔서 해결했습니다.
