### ISSUE TITLE
form 태그 onsubmit 사용하여 javascript 코드를 실행 시 컨트롤러로 이동하지 않는 방법.

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#47]
form 태그 onsubmit 사용하여 javascript 코드를 실행 시 컨트롤러로 이동하지 않는 방법.

form 태그의 onsubmit으로 javascript코드를 실행 했을 경우
1. 해당 javascript 코드 실행
2. controller로 이동
순서로 실행이 됩니다.
만약 controller로 이동을 원치 않으시다

form <onsubmit="실행할 함수(event);"> //1. 이런 식으로 실행할 함수의 인수로 event를 넣습니다.

실행할함수(event) //2.함수의 파라미터에 event를 선언해줍니다.
{
      event.preventDefault(); //3. event.preventDefault()를 호출하면 javascript 코드 실행 이후 컨트롤러로 이동하지 않습니다.
       javascript 코드
}

정리
1. onsubmit=""의 ""안에 들어갈 함수의 인자에 event를 넣어준다
2. 해당 함수의 파라미터로 event를 받아준다.
3. event.preventDefault();함수를 호출해준다.

**Comment by YangHeeChang** [comment]
확인했습니다
