### ISSUE TITLE
로그 찍는 법 공유

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#49]
java 와 javascript에서 로그 찍는 법

바로 console.log();

console.log(출력할 변수); 를 통해서 변수 값이 잘 들어가 있나 콘솔을 통해 확인이 가능하다.

어느 콘솔?
크롬 오른쪽 상단에 .3개 있는 표시 -> 도구 더보기 -> 개발자 도구 -> console에서 확인이 가능하다.

**Comment by JJW1223** [comment]
행님 혹시 파싱하는법 아십니꺼

**Comment by jeongseonwoong** [comment]
몰?루

**Comment by jeongseonwoong** [comment]
javascript 에서만 해당되고 자바는 원래대로 System.out.println("")통해서 로그에 출력하시면 됩니다.

**Comment by JJW1223** [comment]
덕분에 html, js 확인하는 작업에 잘 썼습니다.
