### ISSUE TITLE
branch merge 취소 사유

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#61]
![스크린샷 2024-05-13 154856](https://github.com/jeongseonwoong/morbus/assets/84493979/2a19dc22-c7f5-4173-91cb-e434f5f5ea87)
이것저것 시도하기 위해 fork뜬 repository에서 merge할 때 원본 repository로 병합되어서 취소함
#59 #60

**Comment by jeongseonwoong** [comment]
확인
