### ISSUE TITLE
로그인 기능 추가에 따른 "첫 페이지 변경" 에 관하여

### ISSUE THREAD

**Issue by jeongseonwoong** [jeongseonwoong/morbus#65]
로그인 기능을 추가하게 되면서 첫 사이트 화면을 로그인 화면으로 바꾸려고 합니다. 
이에 따라 기존 localhost:8080/morbus.html로 접속하여 첫 화면을 띄우던 방법에서 localhost:8080로 접속하면 로그인 페이지가 뜨도록 바꾸고자 합니다. feature_login mr 이후 적용될 예정이니 참고 바랍니다.

**Comment by JJW1223** [comment]
시른뎅...

**Comment by jeongseonwoong** [comment]
메인 페이지를 첫페이지 그대로 두고 우측 상단에 로그인, 회원가입 태그 이용해서 이동하도록 만들게요
