### ISSUE TITLE
가독성 좋은 폰트 교체 제안

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#66]
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/896f0606-b37c-42b3-ba25-1dd9689efd1e)
좀 더 가독성 좋은 폰트를 찾은 거 같아서 제안해봅니다.
https://cactus.tistory.com/306

**Comment by jeongseonwoong** [comment]
오

**Comment by JJW1223** [comment]
기존 폰트로 계속 진행하겠습니다.
