### ISSUE TITLE
html a태그 href url 연결 문제

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#69]
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/c55d9c38-3db5-4233-94e4-c23817011127)
다른 사이트 url과 똑같이 했는데 연결이 안됩니다.

**Comment by jeongseonwoong** [comment]
feature_diseaseInfo브랜치에서 해결했습니다.
git pull origin feature_diseaseInfo 해보세용
