### ISSUE TITLE
첫 번째 홈페이지 디자인 추천

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#77]
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/52692bcf-23f5-4d52-9d41-6a42fb210f5d)
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/7ae246ba-9c8a-487c-abce-14be78ff3c10)
찾아보니까 멋있는 홈페이지 디자인을 발견해서 공유합니다!!
이 중 더 좋은 거 있거나 위 디자인 중 맘에 드는 거 있으면 코멘트 바랍니다!

**Comment by jeongseonwoong** [comment]
첫번째 디자인 마음에 듭니다.

**Comment by JJW1223** [comment]
첫번째 디자인 참고해서 홈페이지 만들었습니다
