### ISSUE TITLE
데이터 입출력 페이지를 2페이지로 분리

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#81]
데이터베이스의 데이터 출력까지 구현하였으나, 한 페이지 내에 입출력을 구현하려고 하니 오류가 발생
일단 2페이지로 나누어서 구현하겠습니다.

**Comment by jeongseonwoong** [comment]
된거 아니였나요

**Comment by YangHeeChang** [comment]
일단 2페이지로 구현했고, 나중에 한페이지로 구현되도록 해보겠습니다.
