### ISSUE TITLE
datetime 데이터 출력 형태 변환

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#88]
입출력 페이지를 한 페이지로 구현하였으나, datetime 데이터 출력 형태가 이상합니다. 어떻게 고칠까요?
![스크린샷 2024-05-20 172626](https://github.com/jeongseonwoong/morbus/assets/84493979/b08d0aa6-da35-438b-b6ca-4a2500e3431c)

**Comment by JJW1223** [comment]
구현 부분 코드 보내주세요

**Comment by YangHeeChang** [comment]
<div th:each="record : ${records}">
            <span th:text="${record.timestamp}"></span>
            <span th:text="${record.symptom}"></span>
        </div>

**Comment by YangHeeChang** [comment]
![스크린샷 2024-05-20 172926](https://github.com/jeongseonwoong/morbus/assets/84493979/3af4991b-760d-4a09-a4bc-b0dd41361fc8)

**Comment by JJW1223** [comment]
큰따옴표에 +시 추가해보세여

**Comment by jeongseonwoong** [comment]
record.get~~()로 따로 적어보세요

**Comment by YangHeeChang** [comment]
감사합니다. 이대로 해볼게요

**Comment by YangHeeChang** [comment]
성공했습니다.
