### ISSUE TITLE
이미지가 표시되지 않음

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#9]
![스크린샷 2024-04-07 230017](https://github.com/jeongseonwoong/morbus/assets/84493979/4a05d11d-a38f-4cd6-86d3-9c5f7eedb5c9)
이미지 경로가 달라져서 발생함
경로 지정을 상대 경로로 하면 해결 가능할 것으로 보임

**Comment by jeongseonwoong** [comment]
경로 재설정 함

**Comment by jeongseonwoong** [comment]
경로 재설정 함
