### ISSUE TITLE
jparepository 오류

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#93]
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/7f813684-1f03-4167-8899-b90836b0b7a2)
이거 pull하고 홈페이지 실행하다가 이 오류 발생했는데 어떻게 해결하는지 아시는분

**Comment by jeongseonwoong** [comment]
build.gradle 파일
dependencies에 
implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
추가해보세요

**Comment by JJW1223** [comment]
해결됐습니다 감사합니다
