### ISSUE TITLE
symbol을 찾지 못하는 문제

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#94]
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/0a0aa67c-1fcc-4922-b234-66889c732d27)
main pull 후 발생한 문제입니다.

**Comment by YangHeeChang** [comment]
#95 해결되면 같이 해결될 꺼 같은데 여전히 안되나요?

**Comment by JJW1223** [comment]
해결됬습니다 감사합니다
