### ISSUE TITLE
java: package jakarta.persistence does not exist 문제

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#95]
![스크린샷 2024-05-22 135817](https://github.com/jeongseonwoong/morbus/assets/85469701/3e4f0bb4-d0ae-4846-a0f8-ca140d674ad8)
java: package jakarta.persistence does not exist
main pull 하고 실행했을 시 발생한 문제입니다.

**Comment by YangHeeChang** [comment]
Github에 있는 build.gradle 복사해서 덮어쓰고 file에서 invalid cashes ㄱㄱ

**Comment by JJW1223** [comment]
오 해결됬음 땡큐
