### ISSUE TITLE
증상기록지 디자인 리뉴얼

### ISSUE THREAD

**Issue by YangHeeChang** [jeongseonwoong/morbus#96]
![Screenshot_20240522_140148_Chrome](https://github.com/jeongseonwoong/morbus/assets/84493979/4e66e6e0-ad85-4d17-8bd9-de867251da2d)
시간이랑 증상 출력을 저런 노트에 적은 것처럼 나오게 꾸며볼까 하는데 어떰?

**Comment by JJW1223** [comment]
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/70f75362-4ca3-49ef-bfbd-7628393d601e)
아니면 병원 차트처럼 꾸미는 거 어떤가여

**Comment by YangHeeChang** [comment]
일단 확인했습니다

**Comment by YangHeeChang** [comment]
![스크린샷 2024-05-23 163331](https://github.com/jeongseonwoong/morbus/assets/84493979/007aab04-ebf2-4078-bdb9-5eaa5b10d29b)
굿?
