### ISSUE TITLE
로그아웃 기능 추가 및 버튼 위치 추천

### ISSUE THREAD

**Issue by JJW1223** [jeongseonwoong/morbus#97]
![image](https://github.com/jeongseonwoong/morbus/assets/85469701/23e51a7b-a4ff-4862-94fa-b655ec73c49b)
로그아웃 기능을 추가해야할 것 같습니다.
그리고 로그아웃 버튼 위치도 추천 받습니다

**Comment by YangHeeChang** [comment]
![스크린샷 2024-05-24 094043](https://github.com/jeongseonwoong/morbus/assets/84493979/e859ea6c-1726-4607-8baa-a4c01e7bffa7)
이런 식으로 사이드바에도 추가 가능한가요?

**Comment by JJW1223** [comment]
사이드바에 로그인 기능 추가 완료했고, 버튼 위치 이대로 픽스하겠습니다.
